name       : mesalib
version    : 18.0.2
release    : 88
source     :
    - https://mesa.freedesktop.org/archive/mesa-18.0.2.tar.xz : 98fa159768482dc568b9f8bf0f36c7acb823fa47428ffd650b40784f16b9e7b3
homepage   : http://mesa3d.org/
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Mesa is an OpenGL compatible 3D graphics library.
optimize   :
    - no-symbolic
emul32     : yes
libsplit   : no
patterns   :
    - devel :
        - /usr/lib64/lib*GL.so
        - /usr/lib64/libGL*.so
        - /usr/lib64/libOS*.so
        - /usr/lib64/libg*.so
        - /usr/lib64/libwayland*.so
        - /usr/lib64/libxa*.so
    - 32bit-devel :
        - /usr/lib32/lib*GL.so
        - /usr/lib32/libGL*.so
        - /usr/lib32/libOS*.so
        - /usr/lib32/libg*.so
        - /usr/lib32/libwayland*.so
        - /usr/lib32/libxa*.so
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig32(expat)
    - pkgconfig(glproto)
    - pkgconfig32(libdrm)
    - pkgconfig32(libelf)
    - pkgconfig32(libglvnd)
    - pkgconfig32(libva)
    - pkgconfig32(nettle)
    - pkgconfig(presentproto)
    - pkgconfig32(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(xext)
    - pkgconfig32(xdamage)
    - pkgconfig32(xfixes)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - llvm-32bit
    - llvm-devel
    - mako
    - git
    - vim
rundeps    :
    - libglvnd
    - linux-driver-management
    - 32bit :
        - libglvnd-32bit
    - 32bit-devel :
        - libglvnd-32bit-devel
    - devel :
        - libglvnd-devel
description: |
    Mesa is an OpenGL compatible 3D graphics library.
setup      : |
    unset LD_AS_NEEDED
    %apply_patches
    %configure --disable-static \
               --with-clang-libdir=%libdir%/clang \
               --sysconfdir=/etc \
               --enable-texture-float \
               --enable-egl \
               --enable-gles1 \
               --enable-gles2 \
               --enable-vdpau \
               --enable-xa \
               --enable-gbm \
               --enable-gallium-egl \
               --enable-gallium-gbm \
               --enable-llvm \
               --enable-glx-tls \
               --enable-nine \
               --enable-gallium-osmesa \
               --with-llvm-shared-libs \
               --enable-shared-glapi \
               --with-vulkan-drivers=intel,radeon \
               --with-egl-platforms="drm,x11,wayland" \
               --with-gallium-drivers="nouveau,r300,r600,radeonsi,svga,swrast,swr,virgl" \
               --enable-dri3 \
               --enable-libglvnd
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install

    # Remove libGLES* files provided by libglvnd
    rm -f $installdir/%libdir%/libGLES*

    # Add missing symlink
    ln -s libGLX_mesa.so.0 $installdir/%libdir%/libGLX_indirect.so.0
