name       : mesalib
version    : 19.2.3
release    : 127
source     :
    - https://mesa.freedesktop.org/archive/mesa-19.2.3.tar.xz : 5ee6e42504fe41dcc9a6eba26982656a675b2550a640946f463927ed7f1c5047
homepage   : http://mesa3d.org/
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Mesa is an OpenGL compatible 3D graphics library.
description: |
    Mesa is an OpenGL compatible 3D graphics library.
optimize   :
    - no-symbolic
emul32     : yes
libsplit   : no
patterns   :
    - devel :
        - /usr/lib64/lib*GL.so
        - /usr/lib64/libGL*.so
        - /usr/lib64/libOS*.so
        - /usr/lib64/libg*.so
        - /usr/lib64/libwayland*.so
        - /usr/lib64/libxa*.so
    - 32bit-devel :
        - /usr/lib32/lib*GL.so
        - /usr/lib32/libGL*.so
        - /usr/lib32/libOS*.so
        - /usr/lib32/libg*.so
        - /usr/lib32/libwayland*.so
        - /usr/lib32/libxa*.so
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig32(expat)
    - pkgconfig(glproto)
    - pkgconfig32(libdrm)
    - pkgconfig32(libelf)
    - pkgconfig32(libglvnd)
    - pkgconfig32(libunwind)
    - pkgconfig32(libva)
    - pkgconfig32(nettle)
    - pkgconfig(presentproto)
    - pkgconfig32(vdpau)
    - pkgconfig32(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(xext)
    - pkgconfig32(xdamage)
    - pkgconfig32(xfixes)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xrandr)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - git
    - llvm-32bit-devel
    - llvm-clang-32bit-devel
    - llvm-devel
    - mako
rundeps    :
    - libglvnd
    - linux-driver-management
    - 32bit :
        - libglvnd-32bit
    - 32bit-devel :
        - libglvnd-32bit-devel
    - devel :
        - libglvnd-devel
environment: |
    export PYTHON=/usr/bin/python3
setup      : |
    %apply_patches
    if [[ ! -z $EMUL32BUILD ]]; then
          export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
          export EXTRA_ARGS="--cross-file $pkgfiles/llvm32.native --libdir=/usr/lib32"
    else
          export PKG_CONFIG_PATH="/usr/lib64/pkgconfig"
          export EXTRA_ARGS=""
    fi
    %meson_configure $EXTRA_ARGS \
        -Dplatforms=drm,x11,wayland \
        -Dgallium-drivers=iris,nouveau,r300,r600,radeonsi,svga,swrast,virgl \
        -Dgallium-vdpau=true \
        -Dgallium-xa=true \
        -Dgallium-nine=true \
        -Dvulkan-drivers=amd,intel \
        -Dshader-cache=true \
        -Dgles2=true \
        -Dgbm=true \
        -Degl=true \
        -Dglvnd=true \
        -Dllvm=true \
        -Dosmesa=gallium
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Remove libGLES* files provided by libglvnd
    rm -f $installdir/%libdir%/libGLES*

    # Add missing symlink
    ln -s libGLX_mesa.so.0 $installdir/%libdir%/libGLX_indirect.so.0
